# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

#########################################################
##### auto generated code, keep for later reference #####
#########################################################
# default_platform(:ios)
#
# platform :ios do
#   desc "Push a new release build to the App Store"
#   lane :release do
#     increment_build_number(xcodeproj: "mZone Poker.xcodeproj")
#     build_app(scheme: "mZone Poker")
#     upload_to_app_store
#   end
# end

##########################################
##### below section, follow tutorial #####
##########################################

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.100.1"

default_platform :ios

platform :ios do
  desc "Creating a code signing certificate and provisioning profile"
  lane :provision do
    produce(
      app_name: 'Pocker huysamdua86gmailcom',
      language: 'English',
      app_version: '1.0',
      sku: 'HDPH270718'
    )
    cert
    sigh(force: true)
  end

  desc "Take screenshots"
  lane :screenshot do
    snapshot
  end

  desc "Create ipa"
  lane :build do
    increment_build_number
    gym
  end

  error do |lane, exception|
  # This block is called if there was an error running a lane.
  end
end
